name: pull-request-to-main

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:    
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Postgres Client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Run Make
        env:
          PG_USERNAME: ${{ secrets.PG_USERNAME }}
          PG_DATABASE: ${{ secrets.PG_DATABASE }}
          PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
          PG_HOST: ${{ secrets.PG_HOST }}
          BUCKET: ${{ secrets.BUCKET }}
          TRANSFORM_BUCKET: ${{ secrets.TRANSFORM_BUCKET }}
          TEST_PG_DATABASE: postgres
          TEST_PG_PASSWORD: postgres
          TEST_PG_USERNAME: postgres
          TEST_PG_PORT: 5432
        run: |
          make requirements
          PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -f ./tests/test_db/setup_dbs.sql
          python ./tests/test_db/test_db_utils.py
          make dev-setup
          make run-checks

  check-infrastructure:
    name: check-infrastructure
    runs-on: ubuntu-latest
    environment: dev
    needs: run-tests
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan


        